// Code generated by mockery v2.53.4. DO NOT EDIT.

package details

import mock "github.com/stretchr/testify/mock"

// MockStorageRepository is an autogenerated mock type for the StorageRepository type
type MockStorageRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *MockStorageRepository) GetByID(id uint64) (*Details, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *Details
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*Details, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *Details); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Details)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockStorageRepository creates a new instance of MockStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageRepository {
	mock := &MockStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
