// Code generated by mockery v2.53.4. DO NOT EDIT.

package details

import (
	context "context"
	domaindetails "details-microservice/internal/domain/details"

	mock "github.com/stretchr/testify/mock"
)

// MockStorageRepository is an autogenerated mock type for the StorageRepository type
type MockStorageRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockStorageRepository) GetByID(ctx context.Context, id string) (*domaindetails.Details, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domaindetails.Details
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domaindetails.Details, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domaindetails.Details); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domaindetails.Details)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockStorageRepository creates a new instance of MockStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageRepository {
	mock := &MockStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
