// Code generated by mockery v2.53.4. DO NOT EDIT.

package reader

import (
	context "context"
	details "details-microservice/internal/domain/details"

	mock "github.com/stretchr/testify/mock"
)

// MockDetailsService is an autogenerated mock type for the DetailsService type
type MockDetailsService struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDetailsService) GetByID(ctx context.Context, id string) (*details.Details, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *details.Details
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*details.Details, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *details.Details); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*details.Details)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDetailsService creates a new instance of MockDetailsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDetailsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDetailsService {
	mock := &MockDetailsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
